### ISSUE TITLE
条件随机场是这么实现的？这么几行代码都敢发

### ISSUE THREAD

**Issue by hecyxy** [fengdu78/lihang-code#33]

**Comment by imageslr** [comment]
你好歹贴一个正确 的啊

**Comment by hecyxy** [comment]
> 你好歹贴一个正确 的啊

你可能会吐槽公司制度、国家制度不好，你去创个公司、建个国家？

**Comment by imageslr** [comment]
> > 你好歹贴一个正确 的啊
> 
> 你可能会吐槽公司制度、国家制度不好，你去创个公司、建个国家？

你可真能扯，让你写两行代码，你直接上升到公司国家了。这是你会不会的问题。你标题里说“条件随机场是这么实现的？” 整的我还以为你会写呢。

**Comment by hecyxy** [comment]
> > > 你好歹贴一个正确 的啊
> > 
> > 
> > 你可能会吐槽公司制度、国家制度不好，你去创个公司、建个国家？
> 
> 你可真能扯，让你写两行代码，你直接上升到公司国家了。这是你会不会的问题。你标题里说“条件随机场是这么实现的？” 整的我还以为你会写呢。

逻辑太差，拜拜

**Comment by imageslr** [comment]
你这逻辑感人。你觉得国家制度有问题，是你想改就能改的？你觉得这代码有问题，那你就贴个没问题的代码啊，谁拦着你不让你发代码了么？不发代码，又在这里吐槽代码有问题，这不是口嗨？开源社区，没人阻止你参与。吐槽的不是你说代码问题，吐槽的是你光说还没给个理由，那你就不是来讨论的呗。想口嗨我建议你去买冰箱，买冰箱不需要你会制冷。

**Comment by imageslr** [comment]
这是指出问题的正确姿势：#19 ， #16

**Comment by fengdu78** [comment]
确实本人水平有限，欢迎有合适内容PR

**Comment by hecyxy** [comment]
> 确实本人水平有限，欢迎有合适内容PR

你这么说，我倒觉得自己语气太差，多包涵，书中的条件随机场太过简单，建议看一下成熟的crf实现；
